// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqotdnvwyjhyiqzbefpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xb3RkbnZ3eWpoeWlxemJlZnBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMzU1NDQsImV4cCI6MjA3MzcxMTU0NH0.FK5nOddI6jwc9yxwDt5QPO89Yg7YrtKUnHieEu1AIRg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});